/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p1_carlomenjivar20551123;

/**
 *
 * @author marcellomenjivarmontesdeoca
 */
public class ejercicioDos extends javax.swing.JFrame {

    /**
     * Creates new form ejercicioDos
     */
    public subMenuProyecto frameanterior;
    private int numero;
    
    public ejercicioDos() {
        initComponents();
    }
    
    public void setFrameAnterior(subMenuProyecto frameanterior){
        this.frameanterior = frameanterior;
    }
    
    public void setNumero(int numero){
        this.numero = numero;
        this.soledadTxt.setText(Integer.toString(numero));
    }
    
    public int getNumero(){
        return this.numero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        soledadTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        soledadButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        solucionSoledad = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regresar.setText("Regresar");
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });

        jLabel1.setText("Soledad");

        soledadButton.setText("Soledad");
        soledadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soledadButtonMouseClicked(evt);
            }
        });

        solucionSoledad.setColumns(20);
        solucionSoledad.setRows(5);
        jScrollPane1.setViewportView(solucionSoledad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regresar)
                        .addGap(18, 18, 18)
                        .addComponent(soledadButton))
                    .addComponent(soledadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soledadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresar)
                    .addComponent(soledadButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        // TODO add your handling code here:
        this.frameanterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarMouseClicked

    private void soledadButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soledadButtonMouseClicked
        // TODO add your handling code here:
        this.solucionSoledad.setText(Soledad());
    }//GEN-LAST:event_soledadButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicioDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicioDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicioDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicioDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicioDos().setVisible(true);
            }
        });
    }
    
    public String Soledad(){
        
        String soledad = Integer.toString(this.getNumero());
        int len = Integer.toString(this.getNumero()).length();
        
        int [] sol = new int[len];
    
        
        for(int i=0; i < soledad.length(); i++){
            sol[i] = Character.getNumericValue(soledad.charAt(i));    
        }
        
        int [] solucion = calcularSoledad(sol); 
        
        String oracion = ("El Numero más solitario es "+Integer.toString(solucion[0]) + " por que su nivel de soledad es" + Integer.toString(solucion[1]));

        return oracion;
    }
    
    public int [] calcularSoledad(int[] soledad){
        
        // [posicion, sumatoriasoledad]
        int[] Soledad = new int[2];
        
        int sumatoriaSoledad = 0;
        int sumatoriaComparar = 0;
        
        for(int i = 0; i < soledad.length; i++){
            sumatoriaComparar = sumatoriaSoledad(i, soledad);
            System.out.println(sumatoriaComparar);
            
            if(i == 0){
                sumatoriaSoledad = sumatoriaComparar;
                Soledad[0]=i;
                Soledad[1]=sumatoriaSoledad;
            }else{
                if(sumatoriaComparar <= sumatoriaSoledad){
                    sumatoriaSoledad = sumatoriaComparar;
                    Soledad[0]=i;
                    Soledad[1]=sumatoriaSoledad;
                }
            }   
        }
        
        return Soledad;
    }
    
    public int sumatoriaSoledad(int pos, int [] soledad){
        
        int sumatoria = soledad[pos];
        
        int min;
        int max;
        
        if((pos-soledad[pos])<0){
            min = 0;
        }else{
            min=pos-soledad[pos];
        }
        
        if((pos+soledad[pos])>=soledad.length){
            max=soledad.length-1;
        }else{
            max=pos+soledad[pos];
        }
        
        for(int i = pos-1; i>=min; i--){
            sumatoria+=soledad[i];
        }
        
        for(int i= pos+1; i<=max; i++){
            sumatoria+=soledad[i];
        }
        
        return sumatoria;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresar;
    private javax.swing.JButton soledadButton;
    private javax.swing.JTextField soledadTxt;
    private javax.swing.JTextArea solucionSoledad;
    // End of variables declaration//GEN-END:variables
}
